services:
  zk1:
    image: zookeeper:3.8
    container_name: zk1
    hostname: zk1
    ports:
      - "2181:2181"
    environment:
      ZOO_MY_ID: 1
      ZOO_SERVERS: server.1=zk1:2888:3888;2181 server.2=zk2:2888:3888;2181 server.3=zk3:2888:3888;2181 server.4=zk4:2888:3888;2181 server.5=zk5:2888:3888;2181
      ZOO_4LW_COMMANDS_WHITELIST: "stat, ruok, conf, isro, srvr"
    networks:
      - zk-net

  zk2:
    image: zookeeper:3.8
    container_name: zk2
    hostname: zk2
    ports:
      - "2182:2181"
    environment:
      ZOO_MY_ID: 2
      ZOO_SERVERS: server.1=zk1:2888:3888;2181 server.2=zk2:2888:3888;2181 server.3=zk3:2888:3888;2181 server.4=zk4:2888:3888;2181 server.5=zk5:2888:3888;2181
      ZOO_4LW_COMMANDS_WHITELIST: "stat, ruok, conf, isro, srvr"
    networks:
      - zk-net

  zk3:
    image: zookeeper:3.8
    container_name: zk3
    hostname: zk3
    ports:
      - "2183:2181"
    environment:
      ZOO_MY_ID: 3
      ZOO_SERVERS: server.1=zk1:2888:3888;2181 server.2=zk2:2888:3888;2181 server.3=zk3:2888:3888;2181 server.4=zk4:2888:3888;2181 server.5=zk5:2888:3888;2181
      ZOO_4LW_COMMANDS_WHITELIST: "stat, ruok, conf, isro, srvr"
    networks:
      - zk-net

  zk4:
    image: zookeeper:3.8
    container_name: zk4
    hostname: zk4
    ports:
      - "2184:2181"
    environment:
      ZOO_MY_ID: 4
      ZOO_SERVERS: server.1=zk1:2888:3888;2181 server.2=zk2:2888:3888;2181 server.3=zk3:2888:3888;2181 server.4=zk4:2888:3888;2181 server.5=zk5:2888:3888;2181
      ZOO_4LW_COMMANDS_WHITELIST: "stat, ruok, conf, isro, srvr"
    networks:
      - zk-net

  zk5:
    image: zookeeper:3.8
    container_name: zk5
    hostname: zk5
    ports:
      - "2185:2181"
    environment:
      ZOO_MY_ID: 5
      ZOO_SERVERS: server.1=zk1:2888:3888;2181 server.2=zk2:2888:3888;2181 server.3=zk3:2888:3888;2181 server.4=zk4:2888:3888;2181 server.5=zk5:2888:3888;2181
      ZOO_4LW_COMMANDS_WHITELIST: "stat, ruok, conf, isro, srvr"
    networks:
      - zk-net

networks:
  zk-net:
    external: true